### ISSUE TITLE
Use cockpit for Reinforcement Learning (TD3 Actor Loss)

### ISSUE THREAD

**Issue by f-pfeiffer** [f-dangel/cockpit#31]
Hi,

I would like to use cockpit for Reinforcement Learning. 
The loss of the actor of the TD3 Algorithm is defined as $L=-Q1(s,\pi(s))$, where $Q1$ and $\pi$ are neural networks.
In code it looks like: `L = -qf1(data.observations, actor(data.observations)).mean()`.
Is it somehow possible to use cockpit with this loss?

Best,
Felix

**Comment by f-dangel** [comment]
Hi Felix,

the short answer is that you should still be able to use `cockpit`, however only a sub-set of quantities will work. This is because `cockpit` relies on `backpack` for some quantities, and some of the features offered by `backpack` will likely break for your setup (see [here](https://cockpit.readthedocs.io/en/latest/introduction/good_to_know.html#backpack)).  You will have to exclude those quantities from your cockpit. 

For an example, you can take a look at the [advanced example](https://cockpit.readthedocs.io/en/latest/examples/02_advanced_fmnist.html), and an overview of instruments is [here](https://cockpit.readthedocs.io/en/latest/api/quantities.html). It is currently not documented which quantities will break in your case but you can start with a blank config and add one quantity at a time; you will see exceptions being raised whenever BackPACK does not support your setting. 

Best,
Felix

**Comment by f-pfeiffer** [comment]
Distance, UpdateSize, Alpha, HessMaxEV, HessTrace, TICDiag and TICTrace rely on BackPACK

**Comment by f-dangel** [comment]
Thanks! I think `HessMaxEV` may still work although it uses functionality from BackPACK.

**Comment by f-pfeiffer** [comment]
You are right !
